language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer install --no-interaction

script:
  - php vendor/bin/codecept run --coverage-xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
